### ISSUE TITLE
demo example doesn't work and throws a error on browser console.

### ISSUE THREAD

**Issue by rohitbishnoi** [dirkjanm/videojs-preroll#31]
![screen shot 2018-05-10 at 3 33 28 pm](https://user-images.githubusercontent.com/6151462/39864549-93c6c8c8-5467-11e8-9224-930b164a9674.png)

**Comment by sudoanand** [comment]
Same issue, even on the example.html page provided with this package

**Comment by yringler** [comment]
Not compatible with videojs 7 Should be fixed by #33

**Comment by irieislaw4** [comment]
Same issue. Do you guys already resolve this issue? If so, how? Please I really need your help

**Comment by yringler** [comment]
You can use my fork at https://github.com/yringler/videojs-preroll/
The changes are based on [this stack overflow](https://stackoverflow.com/questions/46880101/videojs-videojs-getcomponent-is-undefined).
There is still a warning, because plugin() has to be replaced with registerPlugion(), but everything works; I'm using it in production now.

EDIT:
I updated to registerPlugin() on my fork.
Note that I didn't publish to NPM, and I didn't yet fully test, as documented in the README there.
It looks like this project isn't being maintained anymore; if someone wants to take over, maybe leave a URL in a comment. Until then, feel free to drop me a PR [at the above repo URL](https://github.com/yringler/videojs-preroll/). In particular, my packages.config could probably use some work.

**Comment by liquidvisual** [comment]
Hi @yringler, I tried your fork repo but the example file still doesn't work for me. There's no /lib in your project. Any advice?

**Comment by yringler** [comment]
Looks like I didn't update it all the way. The lib reference (video is ads)
in the example should be coming from node_modules/ npm if I
remember correctly.

**Comment by liquidvisual** [comment]
@yringler Okay cheers! Sorry I got it working and deleted my post moments after I posted.

**Comment by yringler** [comment]
I was wondering about that. I thought it was a bug in my app at first.
Usually I wouldn't be up at 2am anyway. One of those nights...
Anyway, glad it's working for you.

**Comment by liquidvisual** [comment]
Haha no worries, I know what that's like. I'll likely be up too, trying to get this library integrated with our system. I really hope it works with RTMP streams or it's back to the drawing board.

**Comment by liquidvisual** [comment]
@yringler Sorry to bother, but have you ever used this library with Google IMA ads? Is it possible?

**Comment by yringler** [comment]
No, we only used it with internal ads, directing viewers to other content / partners etc.
Is it possible? IDK. If google provides an API for IMA where you can get some sort of source URL for the ad, you should be able to work it in.

**Comment by yringler** [comment]
https://github.com/googleads/videojs-ima
looks interesting

**Comment by liquidvisual** [comment]
@yringler Thanks for getting back! I just had a look and that library is just what I'm after. :D
